events {}

http {
    server {
        listen 80;

        location / {
            default_type text/html;
            return 200 '<html><body><h1>NGINX Pipeline</h1><p>Deployed using Kubernetes</p></body></html>';
        }
    }
}
