name: NGINX CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build NGINX image
        run: |
          buildah bud \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }} \
            .

      - name: Push image to GHCR
        run: |
          buildah push \
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Push latest image
        run: |
          buildah tag \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            ghcr.io/${{ github.repository }}:latest

          buildah push \
            ghcr.io/${{ github.repository }}:latest
